[package]
name = "loom"
description = "Recover the exact source object, locally"
version.workspace = true
default-run = "loom"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "loom_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "loom-native-host"
path = "src/native_host.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
blake3.workspace = true
chrono.workspace = true
image.workspace = true
loom-core = { path = "../crates/loom-core" }
loom-browser-capture = { path = "../crates/loom-browser-capture" }
opener = "0.8.5"
serde_json.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
uuid.workspace = true

[lints]
workspace = true
